logging:
  level:
    io:
      pivotal: DEBUG

spring:
  application:
    name: articulate

articulate:
  attendee-service:
    uri: http://localhost:8181/attendees

# Using macros that are replaced by maven build
info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@
